### ISSUE TITLE
Creating Users Via Console

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/avalon#104] opened 2020-11-05 15:10 UTC
Need PPID

- [x] Solomon user created

- [x] Alex user created

**Comment by lovinscari** [comment] 2020-11-16 14:37
Adding @AGCooper to test after shib is completed.

**Comment by devanshu-m** [comment] 2020-11-16 21:33
Alex tested his login which was successful.

We need to work on better error handling at some point after user groups ticket is done.

**Comment by lovinscari** [comment] 2020-11-17 17:42
@devanshu-m - since Alex confirmed his login was successful, can we close this issue?

**Comment by devanshu-m** [comment] 2020-11-17 17:44
yes, closing. @lovinscari

**Closed by devanshu-m** 2020-11-17 17:44 UTC
